server:
  port: 8080
spring:
  application:
    name: abas-erp-interview
  datasource:
    url: jdbc:mysql://localhost:3306/abas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true